name: Create Release

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

permissions:
  contents: write  # Required to create releases

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages
        id: get_commits
        run: |
          # Get the last tag (previous release), or set to a default if none exist
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "LAST_TAG=${LAST_TAG}" >> $GITHUB_ENV

          # Get commit messages from the last tag to the current commit
          echo "COMMIT_MESSAGES<<EOF" >> $GITHUB_ENV
          git log --format="- %s" "${LAST_TAG}..HEAD" >> $GITHUB_ENV || echo "No commits found." >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get current date and time
        id: get_date
        run: |
          echo "LAST_UPDATED=$(date -u +"%B %e, %Y at %l:%M %p UTC")" >> $GITHUB_ENV

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0  # Use the same tag for the release
          name: Static Release
          body: |
            Changes in this release:
            ${{ env.COMMIT_MESSAGES }}

            **Last Updated:** ${{ env.LAST_UPDATED }}
          files: |
            GozarCraft - Complementary Settings.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}